// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cell.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cell.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CellDataPB {
class CellDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Cell> {
} _Cell_default_instance_;
class CellSetDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CellSet> {
} _CellSet_default_instance_;

namespace protobuf_cell_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, radius_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, ageb_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, agek_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, ca2p_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, ca2p_avg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, rest_div_times_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, ex_fat_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, in_fat_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, is_touch_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, spr_nat_len_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, pair_index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, fix_origin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, nullified_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, malignant_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, z_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CellSet, cell_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Cell)},
  { 23, -1, sizeof(CellSet)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Cell_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CellSet_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cell.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Cell_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _CellSet_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Cell_default_instance_.DefaultConstruct();
  _CellSet_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\ncell.proto\022\nCellDataPB\"\336\003\n\004Cell\022\r\n\005ind"
      "ex\030\001 \001(\005\022)\n\005state\030\002 \001(\0162\032.CellDataPB.Cel"
      "l.CellState\022\016\n\006radius\030\003 \001(\001\022\014\n\004ageb\030\004 \001("
      "\001\022\014\n\004agek\030\005 \001(\001\022\014\n\004ca2p\030\006 \001(\001\022\020\n\010ca2p_av"
      "g\030\007 \001(\001\022\026\n\016rest_div_times\030\t \001(\005\022\016\n\006ex_fa"
      "t\030\n \001(\001\022\016\n\006in_fat\030\013 \001(\001\022\020\n\010is_touch\030\014 \001("
      "\010\022\023\n\013spr_nat_len\030\r \001(\001\022\022\n\npair_index\030\016 \001"
      "(\005\022\022\n\nfix_origin\030\017 \001(\005\022\021\n\tnullified\030\020 \001("
      "\010\022\021\n\tmalignant\030\021 \001(\010\022\t\n\001x\030\022 \001(\001\022\t\n\001y\030\023 \001"
      "(\001\022\t\n\001z\030\024 \001(\001\"\201\001\n\tCellState\022\t\n\005ALIVE\020\000\022\010"
      "\n\004DEAD\020\001\022\010\n\004DISA\020\002\022\n\n\006UNUSED\020\003\022\007\n\003FIX\020\004\022"
      "\t\n\005BLANK\020\005\022\007\n\003DER\020\006\022\n\n\006MUSUME\020\007\022\007\n\003AIR\020\010"
      "\022\010\n\004MEMB\020\t\022\r\n\tDUMMY_FIX\020\n\")\n\007CellSet\022\036\n\004"
      "cell\030\001 \003(\0132\020.CellDataPB.Cellb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 556);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cell.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cell_2eproto

const ::google::protobuf::EnumDescriptor* Cell_CellState_descriptor() {
  protobuf_cell_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cell_2eproto::file_level_enum_descriptors[0];
}
bool Cell_CellState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Cell_CellState Cell::ALIVE;
const Cell_CellState Cell::DEAD;
const Cell_CellState Cell::DISA;
const Cell_CellState Cell::UNUSED;
const Cell_CellState Cell::FIX;
const Cell_CellState Cell::BLANK;
const Cell_CellState Cell::DER;
const Cell_CellState Cell::MUSUME;
const Cell_CellState Cell::AIR;
const Cell_CellState Cell::MEMB;
const Cell_CellState Cell::DUMMY_FIX;
const Cell_CellState Cell::CellState_MIN;
const Cell_CellState Cell::CellState_MAX;
const int Cell::CellState_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cell::kIndexFieldNumber;
const int Cell::kStateFieldNumber;
const int Cell::kRadiusFieldNumber;
const int Cell::kAgebFieldNumber;
const int Cell::kAgekFieldNumber;
const int Cell::kCa2PFieldNumber;
const int Cell::kCa2PAvgFieldNumber;
const int Cell::kRestDivTimesFieldNumber;
const int Cell::kExFatFieldNumber;
const int Cell::kInFatFieldNumber;
const int Cell::kIsTouchFieldNumber;
const int Cell::kSprNatLenFieldNumber;
const int Cell::kPairIndexFieldNumber;
const int Cell::kFixOriginFieldNumber;
const int Cell::kNullifiedFieldNumber;
const int Cell::kMalignantFieldNumber;
const int Cell::kXFieldNumber;
const int Cell::kYFieldNumber;
const int Cell::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cell::Cell()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cell_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:CellDataPB.Cell)
}
Cell::Cell(const Cell& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&index_, &from.index_,
    reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&index_) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:CellDataPB.Cell)
}

void Cell::SharedCtor() {
  ::memset(&index_, 0, reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&index_) + sizeof(z_));
  _cached_size_ = 0;
}

Cell::~Cell() {
  // @@protoc_insertion_point(destructor:CellDataPB.Cell)
  SharedDtor();
}

void Cell::SharedDtor() {
}

void Cell::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cell::descriptor() {
  protobuf_cell_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cell_2eproto::file_level_metadata[0].descriptor;
}

const Cell& Cell::default_instance() {
  protobuf_cell_2eproto::InitDefaults();
  return *internal_default_instance();
}

Cell* Cell::New(::google::protobuf::Arena* arena) const {
  Cell* n = new Cell;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cell::Clear() {
// @@protoc_insertion_point(message_clear_start:CellDataPB.Cell)
  ::memset(&index_, 0, reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&index_) + sizeof(z_));
}

bool Cell::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CellDataPB.Cell)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 index = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .CellDataPB.Cell.CellState state = 2;
      case 2: {
        if (tag == 16u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::CellDataPB::Cell_CellState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double radius = 3;
      case 3: {
        if (tag == 25u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &radius_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ageb = 4;
      case 4: {
        if (tag == 33u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ageb_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double agek = 5;
      case 5: {
        if (tag == 41u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &agek_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ca2p = 6;
      case 6: {
        if (tag == 49u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ca2p_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ca2p_avg = 7;
      case 7: {
        if (tag == 57u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ca2p_avg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 rest_div_times = 9;
      case 9: {
        if (tag == 72u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rest_div_times_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ex_fat = 10;
      case 10: {
        if (tag == 81u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ex_fat_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double in_fat = 11;
      case 11: {
        if (tag == 89u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &in_fat_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_touch = 12;
      case 12: {
        if (tag == 96u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_touch_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double spr_nat_len = 13;
      case 13: {
        if (tag == 105u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &spr_nat_len_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 pair_index = 14;
      case 14: {
        if (tag == 112u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pair_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 fix_origin = 15;
      case 15: {
        if (tag == 120u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fix_origin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool nullified = 16;
      case 16: {
        if (tag == 128u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &nullified_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool malignant = 17;
      case 17: {
        if (tag == 136u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &malignant_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double x = 18;
      case 18: {
        if (tag == 145u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double y = 19;
      case 19: {
        if (tag == 153u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double z = 20;
      case 20: {
        if (tag == 161u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CellDataPB.Cell)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CellDataPB.Cell)
  return false;
#undef DO_
}

void Cell::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CellDataPB.Cell)
  // int32 index = 1;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->index(), output);
  }

  // .CellDataPB.Cell.CellState state = 2;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->state(), output);
  }

  // double radius = 3;
  if (this->radius() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->radius(), output);
  }

  // double ageb = 4;
  if (this->ageb() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->ageb(), output);
  }

  // double agek = 5;
  if (this->agek() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->agek(), output);
  }

  // double ca2p = 6;
  if (this->ca2p() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->ca2p(), output);
  }

  // double ca2p_avg = 7;
  if (this->ca2p_avg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->ca2p_avg(), output);
  }

  // int32 rest_div_times = 9;
  if (this->rest_div_times() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->rest_div_times(), output);
  }

  // double ex_fat = 10;
  if (this->ex_fat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->ex_fat(), output);
  }

  // double in_fat = 11;
  if (this->in_fat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->in_fat(), output);
  }

  // bool is_touch = 12;
  if (this->is_touch() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->is_touch(), output);
  }

  // double spr_nat_len = 13;
  if (this->spr_nat_len() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->spr_nat_len(), output);
  }

  // int32 pair_index = 14;
  if (this->pair_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->pair_index(), output);
  }

  // int32 fix_origin = 15;
  if (this->fix_origin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->fix_origin(), output);
  }

  // bool nullified = 16;
  if (this->nullified() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->nullified(), output);
  }

  // bool malignant = 17;
  if (this->malignant() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(17, this->malignant(), output);
  }

  // double x = 18;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(18, this->x(), output);
  }

  // double y = 19;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(19, this->y(), output);
  }

  // double z = 20;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(20, this->z(), output);
  }

  // @@protoc_insertion_point(serialize_end:CellDataPB.Cell)
}

::google::protobuf::uint8* Cell::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CellDataPB.Cell)
  // int32 index = 1;
  if (this->index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->index(), target);
  }

  // .CellDataPB.Cell.CellState state = 2;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->state(), target);
  }

  // double radius = 3;
  if (this->radius() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->radius(), target);
  }

  // double ageb = 4;
  if (this->ageb() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->ageb(), target);
  }

  // double agek = 5;
  if (this->agek() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->agek(), target);
  }

  // double ca2p = 6;
  if (this->ca2p() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->ca2p(), target);
  }

  // double ca2p_avg = 7;
  if (this->ca2p_avg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->ca2p_avg(), target);
  }

  // int32 rest_div_times = 9;
  if (this->rest_div_times() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->rest_div_times(), target);
  }

  // double ex_fat = 10;
  if (this->ex_fat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->ex_fat(), target);
  }

  // double in_fat = 11;
  if (this->in_fat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->in_fat(), target);
  }

  // bool is_touch = 12;
  if (this->is_touch() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->is_touch(), target);
  }

  // double spr_nat_len = 13;
  if (this->spr_nat_len() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->spr_nat_len(), target);
  }

  // int32 pair_index = 14;
  if (this->pair_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->pair_index(), target);
  }

  // int32 fix_origin = 15;
  if (this->fix_origin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->fix_origin(), target);
  }

  // bool nullified = 16;
  if (this->nullified() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(16, this->nullified(), target);
  }

  // bool malignant = 17;
  if (this->malignant() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(17, this->malignant(), target);
  }

  // double x = 18;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(18, this->x(), target);
  }

  // double y = 19;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(19, this->y(), target);
  }

  // double z = 20;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(20, this->z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CellDataPB.Cell)
  return target;
}

size_t Cell::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CellDataPB.Cell)
  size_t total_size = 0;

  // int32 index = 1;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->index());
  }

  // .CellDataPB.Cell.CellState state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  // double radius = 3;
  if (this->radius() != 0) {
    total_size += 1 + 8;
  }

  // double ageb = 4;
  if (this->ageb() != 0) {
    total_size += 1 + 8;
  }

  // double agek = 5;
  if (this->agek() != 0) {
    total_size += 1 + 8;
  }

  // double ca2p = 6;
  if (this->ca2p() != 0) {
    total_size += 1 + 8;
  }

  // double ca2p_avg = 7;
  if (this->ca2p_avg() != 0) {
    total_size += 1 + 8;
  }

  // double ex_fat = 10;
  if (this->ex_fat() != 0) {
    total_size += 1 + 8;
  }

  // double in_fat = 11;
  if (this->in_fat() != 0) {
    total_size += 1 + 8;
  }

  // int32 rest_div_times = 9;
  if (this->rest_div_times() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rest_div_times());
  }

  // int32 pair_index = 14;
  if (this->pair_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pair_index());
  }

  // double spr_nat_len = 13;
  if (this->spr_nat_len() != 0) {
    total_size += 1 + 8;
  }

  // int32 fix_origin = 15;
  if (this->fix_origin() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->fix_origin());
  }

  // bool is_touch = 12;
  if (this->is_touch() != 0) {
    total_size += 1 + 1;
  }

  // bool nullified = 16;
  if (this->nullified() != 0) {
    total_size += 2 + 1;
  }

  // bool malignant = 17;
  if (this->malignant() != 0) {
    total_size += 2 + 1;
  }

  // double x = 18;
  if (this->x() != 0) {
    total_size += 2 + 8;
  }

  // double y = 19;
  if (this->y() != 0) {
    total_size += 2 + 8;
  }

  // double z = 20;
  if (this->z() != 0) {
    total_size += 2 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Cell::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CellDataPB.Cell)
  GOOGLE_DCHECK_NE(&from, this);
  const Cell* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Cell>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CellDataPB.Cell)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CellDataPB.Cell)
    MergeFrom(*source);
  }
}

void Cell::MergeFrom(const Cell& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CellDataPB.Cell)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.index() != 0) {
    set_index(from.index());
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
  if (from.radius() != 0) {
    set_radius(from.radius());
  }
  if (from.ageb() != 0) {
    set_ageb(from.ageb());
  }
  if (from.agek() != 0) {
    set_agek(from.agek());
  }
  if (from.ca2p() != 0) {
    set_ca2p(from.ca2p());
  }
  if (from.ca2p_avg() != 0) {
    set_ca2p_avg(from.ca2p_avg());
  }
  if (from.ex_fat() != 0) {
    set_ex_fat(from.ex_fat());
  }
  if (from.in_fat() != 0) {
    set_in_fat(from.in_fat());
  }
  if (from.rest_div_times() != 0) {
    set_rest_div_times(from.rest_div_times());
  }
  if (from.pair_index() != 0) {
    set_pair_index(from.pair_index());
  }
  if (from.spr_nat_len() != 0) {
    set_spr_nat_len(from.spr_nat_len());
  }
  if (from.fix_origin() != 0) {
    set_fix_origin(from.fix_origin());
  }
  if (from.is_touch() != 0) {
    set_is_touch(from.is_touch());
  }
  if (from.nullified() != 0) {
    set_nullified(from.nullified());
  }
  if (from.malignant() != 0) {
    set_malignant(from.malignant());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void Cell::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CellDataPB.Cell)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Cell::CopyFrom(const Cell& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CellDataPB.Cell)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Cell::IsInitialized() const {
  return true;
}

void Cell::Swap(Cell* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cell::InternalSwap(Cell* other) {
  std::swap(index_, other->index_);
  std::swap(state_, other->state_);
  std::swap(radius_, other->radius_);
  std::swap(ageb_, other->ageb_);
  std::swap(agek_, other->agek_);
  std::swap(ca2p_, other->ca2p_);
  std::swap(ca2p_avg_, other->ca2p_avg_);
  std::swap(ex_fat_, other->ex_fat_);
  std::swap(in_fat_, other->in_fat_);
  std::swap(rest_div_times_, other->rest_div_times_);
  std::swap(pair_index_, other->pair_index_);
  std::swap(spr_nat_len_, other->spr_nat_len_);
  std::swap(fix_origin_, other->fix_origin_);
  std::swap(is_touch_, other->is_touch_);
  std::swap(nullified_, other->nullified_);
  std::swap(malignant_, other->malignant_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Cell::GetMetadata() const {
  protobuf_cell_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cell_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Cell

// int32 index = 1;
void Cell::clear_index() {
  index_ = 0;
}
::google::protobuf::int32 Cell::index() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.index)
  return index_;
}
void Cell::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.index)
}

// .CellDataPB.Cell.CellState state = 2;
void Cell::clear_state() {
  state_ = 0;
}
::CellDataPB::Cell_CellState Cell::state() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.state)
  return static_cast< ::CellDataPB::Cell_CellState >(state_);
}
void Cell::set_state(::CellDataPB::Cell_CellState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.state)
}

// double radius = 3;
void Cell::clear_radius() {
  radius_ = 0;
}
double Cell::radius() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.radius)
  return radius_;
}
void Cell::set_radius(double value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.radius)
}

// double ageb = 4;
void Cell::clear_ageb() {
  ageb_ = 0;
}
double Cell::ageb() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.ageb)
  return ageb_;
}
void Cell::set_ageb(double value) {
  
  ageb_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.ageb)
}

// double agek = 5;
void Cell::clear_agek() {
  agek_ = 0;
}
double Cell::agek() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.agek)
  return agek_;
}
void Cell::set_agek(double value) {
  
  agek_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.agek)
}

// double ca2p = 6;
void Cell::clear_ca2p() {
  ca2p_ = 0;
}
double Cell::ca2p() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.ca2p)
  return ca2p_;
}
void Cell::set_ca2p(double value) {
  
  ca2p_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.ca2p)
}

// double ca2p_avg = 7;
void Cell::clear_ca2p_avg() {
  ca2p_avg_ = 0;
}
double Cell::ca2p_avg() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.ca2p_avg)
  return ca2p_avg_;
}
void Cell::set_ca2p_avg(double value) {
  
  ca2p_avg_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.ca2p_avg)
}

// int32 rest_div_times = 9;
void Cell::clear_rest_div_times() {
  rest_div_times_ = 0;
}
::google::protobuf::int32 Cell::rest_div_times() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.rest_div_times)
  return rest_div_times_;
}
void Cell::set_rest_div_times(::google::protobuf::int32 value) {
  
  rest_div_times_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.rest_div_times)
}

// double ex_fat = 10;
void Cell::clear_ex_fat() {
  ex_fat_ = 0;
}
double Cell::ex_fat() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.ex_fat)
  return ex_fat_;
}
void Cell::set_ex_fat(double value) {
  
  ex_fat_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.ex_fat)
}

// double in_fat = 11;
void Cell::clear_in_fat() {
  in_fat_ = 0;
}
double Cell::in_fat() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.in_fat)
  return in_fat_;
}
void Cell::set_in_fat(double value) {
  
  in_fat_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.in_fat)
}

// bool is_touch = 12;
void Cell::clear_is_touch() {
  is_touch_ = false;
}
bool Cell::is_touch() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.is_touch)
  return is_touch_;
}
void Cell::set_is_touch(bool value) {
  
  is_touch_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.is_touch)
}

// double spr_nat_len = 13;
void Cell::clear_spr_nat_len() {
  spr_nat_len_ = 0;
}
double Cell::spr_nat_len() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.spr_nat_len)
  return spr_nat_len_;
}
void Cell::set_spr_nat_len(double value) {
  
  spr_nat_len_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.spr_nat_len)
}

// int32 pair_index = 14;
void Cell::clear_pair_index() {
  pair_index_ = 0;
}
::google::protobuf::int32 Cell::pair_index() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.pair_index)
  return pair_index_;
}
void Cell::set_pair_index(::google::protobuf::int32 value) {
  
  pair_index_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.pair_index)
}

// int32 fix_origin = 15;
void Cell::clear_fix_origin() {
  fix_origin_ = 0;
}
::google::protobuf::int32 Cell::fix_origin() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.fix_origin)
  return fix_origin_;
}
void Cell::set_fix_origin(::google::protobuf::int32 value) {
  
  fix_origin_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.fix_origin)
}

// bool nullified = 16;
void Cell::clear_nullified() {
  nullified_ = false;
}
bool Cell::nullified() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.nullified)
  return nullified_;
}
void Cell::set_nullified(bool value) {
  
  nullified_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.nullified)
}

// bool malignant = 17;
void Cell::clear_malignant() {
  malignant_ = false;
}
bool Cell::malignant() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.malignant)
  return malignant_;
}
void Cell::set_malignant(bool value) {
  
  malignant_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.malignant)
}

// double x = 18;
void Cell::clear_x() {
  x_ = 0;
}
double Cell::x() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.x)
  return x_;
}
void Cell::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.x)
}

// double y = 19;
void Cell::clear_y() {
  y_ = 0;
}
double Cell::y() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.y)
  return y_;
}
void Cell::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.y)
}

// double z = 20;
void Cell::clear_z() {
  z_ = 0;
}
double Cell::z() const {
  // @@protoc_insertion_point(field_get:CellDataPB.Cell.z)
  return z_;
}
void Cell::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:CellDataPB.Cell.z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CellSet::kCellFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CellSet::CellSet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cell_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:CellDataPB.CellSet)
}
CellSet::CellSet(const CellSet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      cell_(from.cell_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CellDataPB.CellSet)
}

void CellSet::SharedCtor() {
  _cached_size_ = 0;
}

CellSet::~CellSet() {
  // @@protoc_insertion_point(destructor:CellDataPB.CellSet)
  SharedDtor();
}

void CellSet::SharedDtor() {
}

void CellSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CellSet::descriptor() {
  protobuf_cell_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cell_2eproto::file_level_metadata[1].descriptor;
}

const CellSet& CellSet::default_instance() {
  protobuf_cell_2eproto::InitDefaults();
  return *internal_default_instance();
}

CellSet* CellSet::New(::google::protobuf::Arena* arena) const {
  CellSet* n = new CellSet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CellSet::Clear() {
// @@protoc_insertion_point(message_clear_start:CellDataPB.CellSet)
  cell_.Clear();
}

bool CellSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CellDataPB.CellSet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CellDataPB.Cell cell = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_cell()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CellDataPB.CellSet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CellDataPB.CellSet)
  return false;
#undef DO_
}

void CellSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CellDataPB.CellSet)
  // repeated .CellDataPB.Cell cell = 1;
  for (unsigned int i = 0, n = this->cell_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->cell(i), output);
  }

  // @@protoc_insertion_point(serialize_end:CellDataPB.CellSet)
}

::google::protobuf::uint8* CellSet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CellDataPB.CellSet)
  // repeated .CellDataPB.Cell cell = 1;
  for (unsigned int i = 0, n = this->cell_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->cell(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CellDataPB.CellSet)
  return target;
}

size_t CellSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CellDataPB.CellSet)
  size_t total_size = 0;

  // repeated .CellDataPB.Cell cell = 1;
  {
    unsigned int count = this->cell_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->cell(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CellSet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CellDataPB.CellSet)
  GOOGLE_DCHECK_NE(&from, this);
  const CellSet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CellSet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CellDataPB.CellSet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CellDataPB.CellSet)
    MergeFrom(*source);
  }
}

void CellSet::MergeFrom(const CellSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CellDataPB.CellSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cell_.MergeFrom(from.cell_);
}

void CellSet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CellDataPB.CellSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CellSet::CopyFrom(const CellSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CellDataPB.CellSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CellSet::IsInitialized() const {
  return true;
}

void CellSet::Swap(CellSet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CellSet::InternalSwap(CellSet* other) {
  cell_.UnsafeArenaSwap(&other->cell_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CellSet::GetMetadata() const {
  protobuf_cell_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cell_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CellSet

// repeated .CellDataPB.Cell cell = 1;
int CellSet::cell_size() const {
  return cell_.size();
}
void CellSet::clear_cell() {
  cell_.Clear();
}
const ::CellDataPB::Cell& CellSet::cell(int index) const {
  // @@protoc_insertion_point(field_get:CellDataPB.CellSet.cell)
  return cell_.Get(index);
}
::CellDataPB::Cell* CellSet::mutable_cell(int index) {
  // @@protoc_insertion_point(field_mutable:CellDataPB.CellSet.cell)
  return cell_.Mutable(index);
}
::CellDataPB::Cell* CellSet::add_cell() {
  // @@protoc_insertion_point(field_add:CellDataPB.CellSet.cell)
  return cell_.Add();
}
::google::protobuf::RepeatedPtrField< ::CellDataPB::Cell >*
CellSet::mutable_cell() {
  // @@protoc_insertion_point(field_mutable_list:CellDataPB.CellSet.cell)
  return &cell_;
}
const ::google::protobuf::RepeatedPtrField< ::CellDataPB::Cell >&
CellSet::cell() const {
  // @@protoc_insertion_point(field_list:CellDataPB.CellSet.cell)
  return cell_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CellDataPB

// @@protoc_insertion_point(global_scope)
